### ISSUE TITLE
Command to End Interrogation 

### ISSUE THREAD

**Issue by UWPA** [bazooka-codes/csgo-interrogate-plugin#1]
If the map vote menu appears when in an interrogation then you can't end the interrogation without rejoining/disconnecting.
A solution to this would be a command such as "endintg" or just allow !intg to cancel the interrogation if there's already one active,

**Comment by bazookaCodes** [comment]
Ok I added support that if the ending menu is closed, the interrogation will be ended as well. As a heads up, the interrogation will also end on map change regardless. Thank you for bringing this to my attention.
